#!/bin/bash

# Copyright (c) 2020 - 2025 Pawel Drzycimski
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

unif="unif"
incr="incr"

build=1

pushd ./test/ &&
if [ $# -ne 0 ]; then
  if [ $1 == $unif ]; then
    cp makefiles/Makefile_unif ./Makefile &&
    make clean
  elif [ $1 == $incr ]; then
    cp makefiles/Makefile_incr ./Makefile &&
    make clean
  else
    make -j6 $1
    build=0
  fi
fi

if [ $build -eq 1 ]; then
  if [ $# -eq 2 ]; then
    make -j8 $2
  else
    make -j8
  fi
fi

popd
